### ISSUE TITLE
Sell order error

### ISSUE THREAD

**Issue by subevilx** [fj317/PumpBot#40] opened 2021-02-19 10:47 UTC
Coin pair: bnb
Buy order has been made!
Processing sell order.
A BinanceAPI error has occurred. Code = -2010
The relationship of the prices for the orders is not correct.Please use https://github.com/binance/binance-spot-api-docs/blob/master/errors.md to find greater details on error codes before raising an issue.

**Comment by fj317** [comment] 2021-02-19 15:31
Duplicate of #29.

**Closed** 2021-03-07 14:10 UTC
Labels: bug, duplicate
