### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by ernestonee** [fj317/PumpBot#34] opened 2021-02-16 20:04 UTC
when buying some coins im getting list index out of range error

**Comment by fj317** [comment] 2021-02-16 20:13
Does this occurring on the buying or selling part of the program? Or both?

**Comment by ernestonee** [comment] 2021-02-16 20:57
Only on the selling part

**Comment by fj317** [comment] 2021-02-17 13:29
I think this may be related to #29. Specifically the stopPrice and stopLimitPrice parameters in the OCO sell order. I'm trying to fix this bug but it seems very random and is hard to reproduce.

**Comment by dodens** [comment] 2021-02-17 14:23
I have the same error now, i think it's the line "coinOrderInfo           = order['fills'][0]". 
Now I'm only testing buying, i've commented out  coinPriceBought and coinOrderQty, and i'm getting :
Buy order has been made!
list index out of range

**Comment by fj317** [comment] 2021-02-17 15:01
Oh I feel like I might have any idea. I believe the problem is occurring because it is sending a limit order and then asking for the quantity bought, however if the limit order hasn't been fulfilled then the error will occur. I believe I might know a fix for this.

**Comment by DrTTC** [comment] 2021-02-17 15:05
Could this be related to my issue? (#35)

**Comment by fj317** [comment] 2021-02-17 15:19
> 
> 
> Could this be related to my issue? (#35)

Yes I think these are most likely related. I'll put a fix out and then see if that fixes the problem.

**Comment by fj317** [comment] 2021-02-17 15:23
Okay I've just pushed a fix for this. Let me know if you're still getting this error or if it has been resolved please!

**Comment by dodens** [comment] 2021-02-17 15:48
Works fine now.

**Comment by fj317** [comment] 2021-02-17 15:51
Great! Happy that error is fixed finally.

**Closed by fj317** 2021-02-17 15:51 UTC
Labels: bug
