### ISSUE TITLE
"Insufficient balance to sell" error

### ISSUE THREAD

**Issue by salex777** [fj317/PumpBot#28] opened 2021-02-15 16:21 UTC
Hello,
I tried this bot several times. It works but it has some big issues. When it tries to sell the amount of currency it bought, there is an "insufficient balance" error. **It does not calculate the binance fee**, thus the amount of currency purchased cannot be sold. I tried it 3-4 times and I had the same issue (you have to sell it manually), especially if the amount of currency is type of integer. 

Also, in case you want to use 100% of your wallet (it only worked with 85% max for me), there is an insufficient balance error (similar problem with the above).

It sometimes it shows that the api key is invalid but it works after a while.

I just trying to help u with this. Thank you.

**Comment by fj317** [comment] 2021-02-15 16:48
The insufficient balance error can be resolved by the user enabling 'pay with BNB' on their user settings and then ensuring that you hold a dollar or 2 of BNB coin to pay for any transaction fees. I want to implement a feature that checks your BNB balance and if low will top it up however I haven't had time to implement this yet.

I haven't experience an error with using 100% of my wallet, although I don't often use 100% so I'll have to do more testing.
The API being invalid is surprising as I've never had this error myself.
Sometimes the bot works perfectly, and the sell order is made fine. Other times the bot has an error and even with the same config settings I cannot reproduce the bug which makes it far harder to troubleshoot.

**Closed** 2021-02-21 15:33 UTC
Labels: bug, duplicate
